# Judge0 Database Configuration
POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_secure_pass

# Judge0 Redis Configuration
REDIS_PASSWORD=
REDIS_HOST=redis
REDIS_PORT=6379

# Judge0 Server Configuration
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
MAX_EXECUTION_TIME=5
MAX_MEMORY_LIMIT=256000
